homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.0848
  longitude: 14.4112
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 185
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml

# Enables the frontend

frontend: !include themes.yaml

# Enables configuration UI
config:

http:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Enables support for tracking state changes over time
history:
# View all events in a logbook
logbook:

plc_modbus:

switch:
  - platform: modbus_sw
    scan_interval: 1

mqtt:

vera:
  vera_controller_url: http://192.168.1.110:3480/

sensor:
  - platform: mqtt
    state_topic: "prvniPatro/obyvak/teplota"
  - platform: systemmonitor
    resources:
      - type: processor_use
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'beat'

input_datetime:
  chodba_od:
    name: Zapnuti svetel
    has_date: false
    has_time: true
  chodba_do:
    name: Vypnuti svetel
    has_date: false
    has_time: true
  obyvak_intim1_od:
    name: Zapnutí intim 1
    has_date: false
    has_time: true
  obyvak_intim1_do:
    name: Vypnuti intim 1
    has_date: false
    has_time: true
  obyvak_intim2_od:
    name: Zapnuti intim 2
    has_date: false
    has_time: true
  obyvak_intim2_do:
    name: Vypnuti intim 2
    has_date: false
    has_time: true
    
group: !include groups.yaml
automation: !include automations.yaml 
script: !include scripts.yaml
 
